export const billingQueueData = [
  {
    id: "006",
    customerName: "Francois",
    orderNumber: "#006",
    table: "06",
    date: "Wed, 29 May 2024",
    time: "09:15 AM",
    amount: 20.0,
    status: "active",
  },
  {
    id: "005",
    customerName: "Eloise",
    orderNumber: "#005",
    table: "05",
    date: "Wed, 29 May 2024",
    time: "09:00 AM",
    amount: 19.35,
    status: "closed",
  },
  {
    id: "004",
    customerName: "Mike",
    orderNumber: "#004",
    table: "04",
    date: "Wed, 29 May 2024",
    time: "08:15 AM",
    amount: 25.0,
    status: "active",
  },
  {
    id: "003",
    customerName: "Billie",
    orderNumber: "#003",
    table: "03",
    date: "Wed, 29 May 2024",
    time: "08:00 AM",
    amount: 31.5,
    status: "active",
  },
];

export const tablesData = {
  "1st Floor": {
    "2 Persons Table": [
      {
        id: "T-01",
        customer: "Sharon",
        guests: 2,
        time: "09:00 AM",
        status: "served",
      },
      {
        id: "T-02",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
      {
        id: "T-03",
        customer: "Billie",
        guests: 2,
        time: "09:00 AM",
        status: "served",
      },
      {
        id: "T-04",
        customer: "Mike",
        guests: 1,
        time: "09:00 AM",
        status: "served",
      },
      {
        id: "T-05",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
      {
        id: "T-06",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
    ],
    "4 Persons": [
      {
        id: "T-07",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
      {
        id: "T-08",
        customer: "Hyacinth",
        guests: 3,
        time: "01:00 PM",
        status: "reserved",
      },
      {
        id: "T-09",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
      {
        id: "T-10",
        customer: "Justin",
        guests: 4,
        time: "09:30 AM",
        status: "served",
      },
    ],
    "Max 12 Persons": [
      {
        id: "T-11",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
      {
        id: "T-12",
        customer: "Clark",
        guests: 5,
        time: "---",
        status: "served",
      },
      {
        id: "T-13",
        customer: "Meera",
        guests: 10,
        time: "---",
        status: "reserved",
      },
      {
        id: "T-14",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
      {
        id: "T-15",
        customer: null,
        guests: 0,
        time: "---",
        status: "available",
      },
      {
        id: "T-16",
        customer: "Wendy",
        guests: 12,
        time: "---",
        status: "reserved",
      },
    ],
  },
};

export const orderHistoryData = [
  {
    id: "001",
    date: "25/05/2024",
    time: "08:00 AM",
    customerName: "George",
    orderStatus: "Done",
    totalPayment: 35.0,
    paymentStatus: "Paid",
  },
  {
    id: "002",
    date: "25/05/2024",
    time: "08:17 AM",
    customerName: "Charlie",
    orderStatus: "Done",
    totalPayment: 12.5,
    paymentStatus: "Paid",
  },
  {
    id: "003",
    date: "25/05/2024",
    time: "08:30 AM",
    customerName: "Hyacinth",
    orderStatus: "Done",
    totalPayment: 15.25,
    paymentStatus: "Paid",
  },
  {
    id: "004",
    date: "25/05/2024",
    time: "08:35 AM",
    customerName: "Francesca",
    orderStatus: "Done",
    totalPayment: 22.1,
    paymentStatus: "Paid",
  },
  {
    id: "005",
    date: "25/05/2024",
    time: "08:42 AM",
    customerName: "Eliza",
    orderStatus: "Canceled",
    totalPayment: 12.25,
    paymentStatus: "Unpaid",
  },
  {
    id: "006",
    date: "25/05/2024",
    time: "09:00 AM",
    customerName: "Jelly",
    orderStatus: "Done",
    totalPayment: 64.0,
    paymentStatus: "Paid",
  },
  {
    id: "007",
    date: "25/05/2024",
    time: "11:20 AM",
    customerName: "Justin",
    orderStatus: "Done",
    totalPayment: 21.5,
    paymentStatus: "Paid",
  },
  {
    id: "008",
    date: "25/05/2024",
    time: "11:58 AM",
    customerName: "Gregory",
    orderStatus: "Done",
    totalPayment: 16.25,
    paymentStatus: "Paid",
  },
  {
    id: "009",
    date: "25/05/2024",
    time: "12:03 AM",
    customerName: "Alwi",
    orderStatus: "Canceled",
    totalPayment: 19.2,
    paymentStatus: "Unpaid",
  },
  {
    id: "010",
    date: "25/05/2024",
    time: "12:15 PM",
    customerName: "Ganta",
    orderStatus: "Done",
    totalPayment: 12.25,
    paymentStatus: "Paid",
  },
  {
    id: "011",
    date: "25/05/2024",
    time: "01:00 PM",
    customerName: "Zelda",
    orderStatus: "Done",
    totalPayment: 20.12,
    paymentStatus: "Paid",
  },
  {
    id: "001",
    date: "26/05/2024",
    time: "10:08 AM",
    customerName: "Penelope",
    orderStatus: "Done",
    totalPayment: 13.5,
    paymentStatus: "Paid",
  },
  {
    id: "002",
    date: "26/05/2024",
    time: "12:47 AM",
    customerName: "Olivia",
    orderStatus: "Done",
    totalPayment: 10.5,
    paymentStatus: "Paid",
  },
];

export const trackOrderData = [
  {
    name: "Mike",
    table: "Table 04",
    type: "Dine In",
    time: "10:00 AM",
    status: "On Kitchen Hand",
    statusColor: "bg-orange-100 text-orange-600",
    items: [
      "Beef Crowich",
      "Grains Pan Bread",
      "Cheezy Sourdough",
      "Sliced Black Forest",
    ],
    totalItems: 4,
  },
  {
    name: "Billie",
    table: "Table 04",
    type: "Dine In",
    time: "10:00 AM",
    status: "All Done",
    statusColor: "bg-green-100 text-green-600",
    items: ["Beef Crowich", "Cereal Cream Donut", "Cheezy Sourdough"],
    totalItems: 6,
  },
  {
    name: "Richard",
    table: "Table 04",
    type: "Dine In",
    time: "10:00 AM",
    status: "On Kitchen Hand",
    statusColor: "bg-orange-100 text-orange-600",
    items: ["Beef Crowich", "Grains Pan Bread", "Cheezy Sourdough"],
    totalItems: 6,
  },
  {
    name: "Sharon",
    table: "Table 04",
    type: "Dine In",
    time: "10:00 AM",
    status: "On Kitchen Hand",
    statusColor: "bg-orange-100 text-orange-600",
    items: ["Beef Crowich", "Cereal Cream Donut", "Cheezy Sourdough"],
    totalItems: 6,
  },
];
